### ISSUE TITLE
add astro support

### ISSUE THREAD

**Issue by jjenzz** [tokenami/tokenami#148]
i'm not entirely sure if this is even possible atm. i tried using the following snippet from [their docs](https://docs.astro.build/en/guides/typescript/#built-in-html-attributes) which doesn't work:

```tsx
declare namespace astroHTML.JSX {
  interface HTMLAttributes {
  }
}
```

it also doesn't look like the ts-plugin is working. need to investigate if this is possible and try get it working 🙏

**Comment by florian-lefebvre** [comment]
Maybe @ knows more about it?

**Comment by jjenzz** [comment]
it seems that declaring the namespace is working for new attributes, but i can't seem to override the `style` attribute. will keep digging.

**Comment by Princesseuh** [comment]
TypeScript plugins only run `.ts` files, it's not possible to get them running inside file types that needs language servers (Vue, Svelte, Astro etc)

**Comment by jjenzz** [comment]
@Princesseuh i am trying to override the `style` attribute which isn't working here:

```tsx
declare namespace astroHTML.JSX {
  interface HTMLAttributes {
    style?: { "--custom-property"?: number };
  }
}
```

the only way i have managed to get it working is by changing astro types to the following:

```tsx
type StyleObjectOriginal = import('./dist/type-utils.js').Simplify<
  KebabCSSDOMProperties & DOMCSSProperties & AllCSSProperties
>;

interface StyleObject extends StyleObjectOriginal {}
```

and then overriding that interface:

```tsx
declare namespace astroHTML.JSX {
  interface StyleObject {
    "--custom-property"?: number;
  }
}
```

Other libraries provide a specific `CSSProperties` interface like this for this use-case, is this something astro would consider exposing?

**Comment by Princesseuh** [comment]
Ah yes, I didn't understand that you were trying to overwrite the current definition, which doesn't work per TypeScript rules. We could definitely have a `CSSProperties` interface for this use case, would you be willing to contribute it to Astro? Should just be a question of updating this file: https://github.com/withastro/astro/blob/main/packages/astro/astro-jsx.d.ts

> unfortunately tho, regardless of all this, the ts plugin is a fundamental part of the tokenami developer experience atm so i dno if astro support is worth striving for at this stage.

Yeah, it's a very unfortunate part of TypeScript, we're working on some stuff over at Volar to mitigate this, but it's a fair amount of work, unfortunately.

**Comment by jjenzz** [comment]
i'd love to contribute ☺️  i'll do that.

> we're working on some stuff over at Volar to mitigate this

i'll be honest, this is the first time i've heard of Volar. is it possible to build a language server plugin for astro that isn't editor specific/isn't tied to vs code? i'd be interested in exploring that in place of the TS plugin if so.

**Comment by jjenzz** [comment]
one step closer 🎉  https://github.com/withastro/astro/pull/9587

**Comment by jjenzz** [comment]
@Princesseuh apologies for the direct mention but i'm getting a bit stuck here—the tokenami ts plugin works well in `.vue` files. do you have any idea what's making that work there, but not in astro? 

i'd like to explore contributing to astro to get this working, if it'd be welcomed.

**Comment by Princesseuh** [comment]
Astro is still exclusively using a language server, so TypeScript plugins are not loaded in Astro files.

**Comment by jjenzz** [comment]
ah okay, interesting. i had initially wondered if they were proxying Volar language service methods to the TS plugin ones somehow. thanks for clarifying  ☺️

**Comment by jjenzz** [comment]
closing this for now because it doesn't look like this is going to be possible for some time. will recreate this ticket later if things look more plausible.
