### ISSUE TITLE
Feature Request: Support for Dark Mode and Multi-Theme Configurations

### ISSUE THREAD

**Issue by lukebennett88** [tokenami/tokenami#226]
I'm really liking Tokenami so far. It seems incredibly powerful for design systems, which I can see you're already exploring through the examples.

One thing I couldn't find or haven't figured out yet is how to set up different color tokens for `prefers-color-scheme` (e.g., dark mode support).

Is there a way to do this within Tokenami that I've missed, or is it not available yet? Including these features would be especially useful:
- Auto-switching themes with `prefers-color-scheme` media queries.
- An easy API for theme changes within the app at runtime (looks like [you can already do this at build time](https://github.com/tokenami/tokenami?tab=readme-ov-file#user-content-design-systems-with-tokenami)).
- Documentation or examples for setting up themes.

**Comment by lukebennett88** [comment]
As soon as I hit send I found this, I somehow missed it before 🤦‍♂️
https://github.com/tokenami/tokenami/issues/81

Closing as a duplicate.

**Comment by lukebennett88** [comment]
Thanks, I figured that bit out, but I didn't want to apply tokens twice.
Ideally, I can apply a different set of custom properties for dark mode, but that's pretty much how theming works so I marked it as a duplicate 👍

**Comment by jjenzz** [comment]
> Ideally, I can apply a different set of custom properties for dark mode

yep, agreed... i wanna add support so for instance, `--color_primary` can map to a diff value in the diff themes 👍 it's definitely on my list.
