### ISSUE TITLE
Feature request: Global CSS support for user-defined resets

### ISSUE THREAD

**Issue by lukebennett88** [tokenami/tokenami#227]
I couldn't find a way to define global CSS with Tokenami. I can appreciate the argument that this might not be Tokenami's job, having the ability to distribute a CSS reset as part of a design system would be incredibly useful.

Ideally, Tokenami could offer a method to specify global styles for applying a CSS reset. The most straightforward approach might be a top-level key in the configuration:

```typescript
// tokenami.config.ts

export default createConfig({
  globalStyles: {
    "*, *::before, *::after": {
      margin: 0,
      padding: 0,
      boxSizing: "border-box",
    },
    body: {
      fontFamily: "system-ui, sans-serif",
      lineHeight: 1.5,
    },
    // additional reset styles...
  },
  // other Tokenami configuration...
});
```

**Comment by jjenzz** [comment]
@lukebennett88 is #268 enough to cover your needs here?

**Comment by jjenzz** [comment]
i guess this could get a little tedious if you wanted to style all anchors, or headings etc. bcos you'd have to create a new selector for each. 

your idea above could work ofc, just trying to make sure i've explore more tokenami-like ways of achieving it first. it'd be nice not to make the config too complex if it can be avoided but i'll happily go that route if not.
