### ISSUE TITLE
Some selectors don't see to be working as expected

### ISSUE THREAD

**Issue by lukebennett88** [tokenami/tokenami#234]
I tried to configure Tokenami to output [Capsized](https://seek-oss.github.io/capsize/) text, which requires adding styles to an elements `::before` and `::after` pseudo elements.

This might be user error on my part, but when I use the following code:
```tsx
css({
  '--after_content': '""',
  '--after_display': 'table',
  '--after_margin-block-start': 'var(---,-0.125em)',
  '--before_content': '""',
  '--before_display': 'table',
  '--before_margin-block-end': 'var(---,-0.175em)',
})
```
...no pseudo elements are getting styles for me outside of:
```css
[style]:after {
  --after: ;
}

[style]:before {
  --before: ;
}
```

I also had the same issue trying to style `::selection`:

I also noticed in Firefox dev-tools:

> [selection is not supported on highlight pseudo-elements.](https://www.w3.org/TR/css-pseudo-4/#highlight-styling)

It looks like the fallback trick used by Tokenami to enable styling elements that are typically not possible with inline styles might not work here.

Here's a (fairly) minimal repro of the issue:
https://stackblitz.com/~/github.com/lukebennett88/tokenami-repro

**Comment by jjenzz** [comment]
thanks for raising this. it was overlooked when i moved things over to the cascade layer implementation. it's fixed in v0.0.38 🎉

**Comment by jjenzz** [comment]
hmm, i realised that my changes here allow you to add `::selection` styles but if you don't add any then they are reset completely. that's not ideal 🙈  i'll dig into that part some more but `::after` etc. works at least.

**Comment by jjenzz** [comment]
@lukebennett88 ok, `::selection` is working properly now. it's using a less than ideal substring selector for now while i think on this some more, but that might be the only way until [style queries](https://codepen.io/jjenzz/pen/BaEmRpg) are more widely supported.

the intermediary solution is available int v0.0.39.

**Comment by lukebennett88** [comment]
Clever! Just an FYI it looks like this method only works for Chrome (at least it didn't work for me on Firefox of Safari).
Probably fine to consider this progressive enhancement anyway 😅

**Comment by jjenzz** [comment]
yeah style queries are new and aren't widely supported yet unfortunately :( the substring selector in v0.0.39 should work in firefox and safari though, are you seeing problems there?

**Comment by lukebennett88** [comment]
Oh sorry, it was late and I misread your message (thought the CodePen link was using substring selectors and wasn't working for some reason).
Tested the new changes locally and it's working as expected 🎉

**Comment by jjenzz** [comment]
that's a relief 😅  thanks for verifying :)
