### ISSUE TITLE
`tokenami.env.d.ts` usage

### ISSUE THREAD

**Issue by pawelblaszczyk5** [tokenami/tokenami#367]
I have two thoughts about this file which comes from one issue I encountered. I have a lint rule to check for unused variables, so when I started Tokenami project I removed the unused `import type { TokenProperties } from "@tokenami/dev";` part. Later on I added some custom properties to config and I was stuck debugging why it doesn't work.

1. I'm wondering whether that file should be a `.d.ts` file. Most of people will turn on `skipLibCheck` in their tsconfig so we should avoid using `d.ts` files because they don't get typechecked. If that was standard `ts` file I'd notice red squiggly line under every single `TokenProperties` usage.
2. If making it a standard `.ts` file ins't feasible maybe TS plugin could verify some assumptions about this file? 🤔

**Comment by jjenzz** [comment]
i can update the code so that it will only add the import when there are auto-generated properties perhaps
