### ISSUE TITLE
prettier plugin to reorder token properties in specificity order

### ISSUE THREAD

**Issue by jjenzz** [tokenami/tokenami#55]
similar to tailwind, `style={{ '--padding-left': 2, '--padding': 1 }}` would become `style={{ '--padding': 1, '--padding-left': 2 }}` on save because longhand properties win specificity war in tokenami stylesheet.

the css utility overrides params should be used to enforce last-override-wins.

**Comment by ubmit** [comment]
Hey @jjenzz, I'm not sure what do you mean by "prettier rule". Shouldn't we create a plugin?

**Comment by jjenzz** [comment]
@ubmit yep, a prettier plugin [similar to tailwind](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) 👍

**Comment by jjenzz** [comment]
i originally created this ticket bcos tokenami allowed styling directly in the `style` attribute, but now the `css` utility is required. so, i actually think the css utility could handle this without a prettier plugin.

**Comment by jjenzz** [comment]
i'm going to explore solving this with the `css` utility https://github.com/tokenami/tokenami/issues/214
